[build]
builder = "nixpacks"
buildCommand = "npm install && cd server && npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[environments]
production.numReplicas = 1 