[build]
builder = "nixpacks"
buildCommand = "npm install && cd server && npm install && cd ../client && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments]
production.numReplicas = 1 